# These settings are synced to GitHub by https://probot.github.io/apps/settings/
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  private: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
